name: "Code Scanning"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analysis:
    runs-on: ubuntu-latest

    env:
      build-directory: build

    strategy:
      matrix:
        compiler:
          - { cc: clang-11,  cxx: clang++-11 }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{matrix.compiler.cc}} g++-multilib
          cmake -E make_directory ${{env.build-directory}}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Configure (Debug)
        working-directory: ${{env.build-directory}}
        env:
          CC: ${{matrix.compiler.cc}}
          CXX: ${{matrix.compiler.cxx}}
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DMSL_ENABLE_UNIT_TESTS=On

      - name: Build
        working-directory: ${{env.build-directory}}
        run: cmake --build .

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
