name: Ubuntu

on: [push, pull_request]

jobs:
  test:
    name: ${{matrix.compiler.cc}}
    runs-on: ubuntu-20.04

    env:
      build-directory: build

    strategy:
      fail-fast: false
      matrix:
        compiler:
          # GCC Versions
          - { cc: gcc-10, cxx: g++-10 }

          # Clang Versions
          - { cc: clang-11,  cxx: clang++-11 }

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Prepare Environment
        run: |
          sudo apt-get update

          if [[ "${{matrix.compiler.cc}}" =~ "gcc" ]]; then
            sudo apt-get install -y ${{matrix.compiler.cxx}} ${{matrix.compiler.cxx}}-multilib
          else
            sudo apt-get install -y ${{matrix.compiler.cc}} g++-multilib
          fi

          cmake -E make_directory ${{env.build-directory}}

      # Debug Configuration

      - name: Configure (Debug)
        working-directory: ${{env.build-directory}}
        env:
          CC: ${{matrix.compiler.cc}}
          CXX: ${{matrix.compiler.cxx}}
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DMSL_ENABLE_UNIT_TESTS=On

      - name: Build
        working-directory: ${{env.build-directory}}
        run: cmake --build .

      - name: Test
        working-directory: ${{env.build-directory}}
        run: ctest --output-on-failure

      # Release Configuration

      - name: Configure (Release)
        working-directory: ${{env.build-directory}}
        run: cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build (Release)
        working-directory: ${{env.build-directory}}
        run: cmake --build .

      - name: Test (Release)
        working-directory: ${{env.build-directory}}
        run: ctest --output-on-failure

  sanitize:
    name: ${{matrix.compiler.cc}} '${{matrix.sanitizer}}' sanitizer
    runs-on: ubuntu-20.04
    needs: test

    env:
      build-directory: build

    strategy:
      matrix:
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
        sanitizer: [address, undefined]

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Prepare Environment
        run: |
          cmake -E make_directory ${{env.build-directory}}

      - name: Configure
        working-directory: ${{env.build-directory}}
        env:
          CC: ${{matrix.compiler.cc}}
          CXX: ${{matrix.compiler.cxx}}
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DMSL_ENABLE_UNIT_TESTS=On -DCMAKE_CXX_FLAGS="-fsanitize=${{matrix.sanitizer}}"

      - name: Build
        working-directory: ${{env.build-directory}}
        run: cmake --build .

      - name: Test (Sanitize)
        working-directory: ${{env.build-directory}}
        run: ctest --output-on-failure
